### PR TITLE
Deprecate Crushinator options as sending query strings

### PR DESCRIPTION
**Pull request by redoPop**
**Note / update:** #9 is a prerequisite to this.

---

Per #3 sending a query string to the `crush` method is a potential XSS vulnerability and should be deprecated.

Warn about this deprecation via console if a string is passed in.

### CODE REVIEW

**Comment by redoPop** [comment]
Having a second thought about this: in the past we've used query strings for limited rollouts of new Crushinator features. Deprecating query strings means that will no longer be possible.

Before merging this, I think we need a "custom", "adHoc", or even "insecure" option in the options API that can be used to introduce un[vetted](https://github.com/tedconf/js-crushinator-helpers/blob/d4e37b1e90f6b26f0b9e2ea8ae6f91969f12dfd8/src/crushinator.js#L42-L45) Crushinator options.

**Comment by alexdean** [comment]
qq: re your second-thoughts... what can you do in a query string that you can't do in a pojo? what would the custom/adHoc feature look like in implementation? (seeing an example make this clearer to me.)

**Comment by redoPop** [comment]
I can't think of any query string semantics that can't be represented in object form. Which means we could address this by accepting an options POJO that can potentially contain both the helper-specific API options and plain old query parameters, e.g.:

```javascript
crushinator.crush('http://images.ted.com/image.jpg', {
    width: 320,   // JS helper API
    height: 240,  // JS helper API
    c: '200,100'  // Plain old query param
  })
  // => 'https://tedcdnpi-a.akamaihd.net/r/images.ted.com/image.jpg?w=320&h=240&c=200,100'
```

In the current codebase, the "c" property would be ignored because it isn't one pf the vetted API options.

I'd been thinking that we should encapsulate unvetted options in a separate object, like so:

```javascript
crushinator.crush('http://images.ted.com/image.jpg', {
    width: 320,   // JS helper API
    height: 240,  // JS helper API

    custom: {
      c: '200,100'  // Plain old query param
    }
  })
```

...but I'm not sure there's really a need for this.

**Comment by alexdean** [comment]
i can see that keeping the official & experimental options separate might have merit. maybe as a 3rd parameter instead of a nested object?

```javascript
crushinator.crush('http://images.ted.com/image.jpg', {
    width: 320,   // JS helper API
    height: 240,  // JS helper API
  },{
    c: '200,100' // Plain old query param
  }
)
```

rails does something like this for some form helpers, to differentiate options which have special meanings in rails vs. options which should just be passed through to become HTML attributes on the generated form control.

not really that big of a change, and in some ways having the custom stuff explicitly called out does make the method invocation a bit more readable. but overall it seems like avoiding nesting might be easier to manage.

just comments from the peanut gallery i suppose. i def don't have a horse in this race.

**Comment by redoPop** [comment]
I like the third parameter approach. One disadvantage is that it complicates Handlebars support a little.

Instead of object literal notation, Handlebars uses HTML notation for sending named attributes to helpers, like this:

```handlebars
<img src="{{crush "http://images.ted.com/image.jpg" width="320" height="240" custom-c="200,100"}}">
```

(Where `crush` is the name of the helper, `"http://images.ted.com/image.jpg"` is the first argument, and `width`, `height`, and `custom-c` are all named attributes applying to that helper.) These values are then sent to Handlebars helpers in object form like `{ width: '320', height: '240', custom: { c: '200,100' } }`.

This leaves no provision for multiple sets of named attributes, so the separation of experimental options from standard ones would still require an explicit namespace in that situation. There's no technical problem with this, but the lack of parity bugs me a bit.

Keeping unvetted options separated in some way does sound like a good idea to me too, but I also think the associated risks are pretty low. For the sake of simplicity and ease of use, I'm starting to lean a little towards the idea of allowing unvetted property-value pairings in the options object to be treated as regular query parameters, like the first example in my previous comment.

**Comment by redoPop** [comment]
In #8 I took a look at the direct-in-object solution (i.e. allowing additional query parameters to be included directly in the options object, without being namespaced or otherwise separated from the documented helper options). After implementing it I realized that [the potential for naming conflicts is actually much bigger than I'd initially imagined](https://github.com/tedconf/js-crushinator-helpers/pull/8#issuecomment-193541494).

Given this issue, and Handlebars problem with the third parameter approach, I'm reverting to the idea of using a special namespace for custom query parameters.

Now to decide what it should be called.

**Comment by alexdean** [comment]
There are 10 hard problems...

**Pull request merged**
